### ISSUE TITLE
Edge case failures

### ISSUE THREAD

**Issue by PrincessRTFM** [AisteruFire/Velvet#3]
Your alias replacement function has a potential point of failure: if you start or end a grouping of tags with an alias, it will break the search syntax. You looked for optional start/end parentheses independently, and then wrapped the alias expansion in parens regardless. So: `(myalias || some tags)` will expand to `(alias tag 1 || alias tag 2 && alias tag 3) || some tags)`, which leaves unbalanced parens. Suggestion: ignore parens around alias names. Wrap the expansion in parens automatically if you want, although there may be a rare case where someone doesn't want that, but don't remove them from the original if they exist.

Second, wrap your search in `\b` to force alias names to occur only between word boundaries. As is, if I define an alias `light`, then it will be expanded inside `twilight`.

**Comment by AisteruFire** [comment]
About the first point : the point of wrapping aliases in parens (although it doesn't work as intended) was to preserve comparison operators' priorities : if there's an alias `smexy` for `glasses || sexy`, and I search for `smexy && suggestive`, if my alias isn't wrapped it outputs `glasses || sexy && suggestive`, which is interpreted as `glasses || (sexy && suggestive)` instead. Don't you think it would be better to wrap it in all cases ?

About the second : thanks... I'm a bit ashamed I didn't think of this ^^'

**Comment by PrincessRTFM** [comment]
In my original script, I didn't wrap any expansions - if I wanted them wrapped, I put parens around the alias name. That was more a stylistic choice I think, because I couldn't think of any reasons NOT to auto-wrap them, I just wanted to control how the end query looked. I'd ask for a setting, so control freaks like me and any edge cases I haven't thought of won't have problems, but it's not that big a deal. The best thing you can probably do is put a big bold warning on the settings page telling users what you end up doing, especially if you don't auto-wrap.

**Comment by AisteruFire** [comment]
Here's what I put next to a checkbox : `Wrap aliases with parenthesis. This helps avoiding operator priority-based issues.` Seems good enough ?

**Comment by AisteruFire** [comment]
Didn't wait for your response, sorry x)

**Comment by PrincessRTFM** [comment]
That sounds fine. The important bit was to change how you bounded the alias name in your replacement.

I went into beforeSubmit.js to check the new changes, and it looks pretty good. Only a few points of note left, and none are a real big deal:

1. You apply the `::` -> `<preferred join>` replacement on the entire search field value with each applicable replacement. Amusing quirk: if the user puts `::` in the search field, then it will be replaced with their preferred `AND` join operator the first time they have a ditto-op replacement. Not something most people would ever do, cause I don't think `::` is used in any site tags.
2. You're making a single pass. If JS doesn't maintain ordering using for-of, then sub-aliases won't always work. On my system, JS for-in maintains order, and I haven't tested for-of at all, but I don't know if that holds true everywhere. Maybe something like
```javascript
let old = "";
while (old != currentSearch) {
	old = currentSearch;
	currentSearch = expand(currentSearch);
}
```
3. Finally, my script looped over each "word" in the search box (split on whitespace, my aliases were limited to single words) and checked them all individually. This was a little inefficient, but it allowed me to define subaliases within my aliases that would expand out using the same joiner as the searchbox alias. I'm not explaining it well, so here's an example:
```javascript
let aliases = {
	alicoriginals: "princess celestia :: princess luna :: nightmare moon",
	expanded: "`alicoriginals :: princess cadance",
};
let userSearch = "expanded?";
expandString(userSearch) == "princess celestia || princess luna || nightmare moon || princess cadance";
```
See how it expanded `alicoriginals` with the backtick using the same join operator (in this case, `||`) as the alias it was found it? I did this by preprocessing the search string like so: `initial.replace(/\(/g, " ( ").replace(/\)/g, " ) ").trim()` and then splitting on whitespace (`.split(/\s+/)`). Then I looped over each word in the split query, doing the following:

1. Get the last character of the word and check it for magic
2. If it wasn't magic, use the default joiner instead
3. Check the alias for expansion
4. If it isn't defined, return it immediately (side effect: stripped the magic indicators off the end of non-aliased tags)
5. `.replace(/::/g, " :: ")`
6. Loop over each word in the replacement:
	1. If it started with a backtick, call the expander on `(word.substr(1) + lastChar)` to simulate it using the same expansion mode
	2. If it was `::`, replace it with the appropriate joiner
	3. Otherwise, pass it to the expander
7. Return the array concatenated by a single space.

That allowed nested aliases to use the same expansion joiner all the way down. The downside is that it required me to loop over each word in the query, rather than each alias defined. Thinking about it now though, you can pass a function to `String.prototype.replace()` for the replacement, so I might be able to improve that. I'll do some fiddling, see what I can come up with. Once I have my script finished, I'll upload it to a repo here.

**Comment by liamwhite** [comment]
Just make a formal parser for it already.

**Comment by AisteruFire** [comment]
@PrincessRTFM I'm working on your listed issues
@liamwhite What do you mean by "formal parser" ?

**Comment by liamwhite** [comment]
@AisteruFire recursive descent parser for the formal grammar of the search, hand written or automatically generated using a parser generator.

**Comment by AisteruFire** [comment]
I've never heard of it before. If I get it correctly, this could be used here to check for aliases containing ditto operators and replace them without having to use too many Regex to treat all cases ?

**Comment by liamwhite** [comment]
Yes, that is the point of a formal parser.

**Comment by AisteruFire** [comment]
Ok, so I picked the first to come, PEG.js, which seems pretty powerful, but I am having trouble integrating it in my extension. The documentation explains how to use it with Node.js, but it also says I can generate the parser into a .js file, but doesn't tell how to use the parser afterwards. When I execute the parser file in my script, there even is an unknown variable "module", so I don't know whether the parser is supposed to be used in Node.js or in my JS script...

I read about browswerify or something like that, that could allow me to do a require() in my JS code. I'll take a look

**Comment by AisteruFire** [comment]
@PrincessRTFM I didn't quite understand what you meant in your 3rd point : I get that you'd like to be able to apply the same flag to nested aliases, but I didn't quite get the part with the backtick. Could you explain ?
But about this issue, I think it'd be better to leave unflagged aliases replaced with the default operator selected in the settings

**Comment by AisteruFire** [comment]
I am having trouble with the parser code : I can't figure out how to match any word except AND or OR, and PEG.js hasn't implemented a lot of Regex functionnalities... Any idea ?

**Comment by PrincessRTFM** [comment]
The backtick was to indicate which sub-aliases should be expanded with the same magic. That way, you can leave all flags out to expand with the default, append a `?` or `!` to force `OR`/`AND`, or prepend a backtick to just make the subalias always use the same expansion mode that the containing alias was given.

**Comment by AisteruFire** [comment]
@PrincessRTFM Hmm... Interesting concept, I'll give it a look

I gave up with the parser, I think I'm gonna do something with a recursive function, as PrincessRTFM did : it's gonna take a string (the query) and study if it has aliases. If it has, the function will be called again with one of the aliases as parameter. When the function doesn't need to call itself again (which means it's been the deepest for the branch it explored), it returns the string the alias replaced. Something like that :
```
function processQuery(string query [, int dittoFlag [, bool backtick]])
{
    foreach (alias)
    {
        if (query.containsAlias())
        {
            aliasFlag =  alias.lastChar == andFlag ? 2 : alias.lastChar == orFlag ? 1 : backtick ? dittoFlag : defaultFlag;
            query.replace(alias, processQuery(aliasReplacement, aliasFlag, backtick && !(query.containsFlag) || alias.firstChar == `);
        }

        if (query.containsDitto())
                query.replaceDittoByOperator(dittoFlag);
    }

    return query;
}`
```

**Comment by AisteruFire** [comment]
Ok, so I'm having trouble implementing my pseudo-code from last message. Here is my code :
```
/*
	Replaces all aliases in a query.

	query - The query to process
	aliases - An array containing all the aliases structured like this : alias = replacement
	andFlag - The character used as the AND flag
	orFlag - The character used as the OR flag
	defaultFlagValue - The flag to use by default (2 for AND, 1 for OR)
	flagValue - The flag that was used in conjunction with the query in a potential previous call of the function (2 for AND, 1 for OR)
	backtick - Boolean indicating whether or not the query (or a parent alias) was preceded by a backtick

	Returns the query with its aliases replaced.
*/
function processQuery(query, aliases, andFlag, orFlag, defaultFlagValue, flagValue, backtick)
{
	// If no backtick is given, it is by default false
	backtick = backtick || false;

	let regExpDitto = / ?:: ?/g;

	for (let line of aliases)
	{
		let alias = line.split("=")[0].trim(), replacement = line.split("=")[1].trim();
		let regExpAlias = new RegExp("(\\b|`)(" + alias + ")(\\" + andFlag + "|\\" + orFlag + "|\\b)", "ig");

		// Ignoring aliases containing themselves
		if (regExpAlias.test(replacement))
			continue;

		// If the query contains the alias
		if (regExpAlias.test(query))
		{
			let match;

			// Reinitializing the index so that the exec starts from the beginning of the query
			regExpAlias.lastIndex = 0;

			/*
				Browsing every occurence of this alias in the query.

				Returned array :
					[0] Full match
					[1] Backtick
					[2] Alias
					[3] Flag
					[index] Index of matching string
					[input] Full query
			*/
			while ((match = regExpAlias.exec(query)))
			{
				let aliasFlagValue = match[3] == andFlag ? 2 : match[3] == orFlag ? 1 : backtick ? flagValue : defaultFlagValue;

				// Replacing the alias with the query it represents
				query.replace(regExpAlias, processQuery(
					replacement,
					aliases,
					orFlag,
					andFlag,
					defaultFlagValue,
					aliasFlagValue,
					backtick && !match[3] || match[1]	// Either there was a backtick on a parent alias and there is no new flag for this alias, or there is a backtick on this alias
				));
			}
		}
	}

	// If the query contains ditto operators
	if (regExpDitto.test(query))
		query.replace(regExpDitto, flagValue == 2 ? " AND " : flagValue == 1 ? " OR " : " ");

	return query;
}
```

I can't figure out why, but when `query` contains an alias, the function gets stuck in an infinite loop. However, I was careful never to work twice on the same string. Does one of you see where this is going wrong ?

**Comment by AisteruFire** [comment]
Done ! [Version 1.1.4](https://github.com/AisteruFire/Velvet/commit/ac4042f6494dc79b4352344c8bc7ceb7b343efe8) contains backtick support and recursive processing of the aliases ! Pretty much everything you asked for, right ? ;)

If you'll excuse me, I've done enough for one day. Feel free to post what you think about and what you'd change !
